[macOS.Tahoe]
"What's new for enterprise in macOS Tahoe" = "https://support.apple.com/en-us/124963"
"What's new in the updates for macOS Tahoe" = "https://support.apple.com/en-us/122868"
"macOS Tahoe is compatible with these computers" = "https://support.apple.com/en-us/122867"

[macOS.Sequoia]
"What's new for enterprise in macOS Sequoia" = "https://support.apple.com/en-ca/121011"
"What's new in the updates for macOS Sequoia" = "https://support.apple.com/en-ca/120283"
"macOS Sequoia is compatible with these computers" = "https://support.apple.com/en-us/120282"

[macOS.Sonoma]
"What's new for enterprise in macOS Sonoma" = "https://support.apple.com/en-ca/109030"
"What's new in the updates for macOS Sonoma" = "https://support.apple.com/en-ca/109035"
"macOS Sonoma is compatible with these computers" = "https://support.apple.com/en-us/105113"

[macOS.Ventura]
"What's new for enterprise in macOS Ventura" = "https://support.apple.com/en-ca/HT213327"
"What's new in the updates for macOS Ventura" = "https://support.apple.com/en-ca/106337"
"macOS Ventura is compatible with these computers" = "https://support.apple.com/en-us/102861"

[macOS.Monterey]
"What's new for enterprise in macOS Monterey" = "https://support.apple.com/en-ca/103271"
"What's new in the updates for macOS Monterey" = "https://support.apple.com/en-ca/106339"

[iOS."18"]
"What's new for enterprise in iOS/iPadOS 18" = "https://support.apple.com/en-ca/121158"
"What's new in the updates for iOS/iPadOS 18" = "https://support.apple.com/en-ca/121161"

[iOS."17"]
"What's new for enterprise in iOS/iPadOS 17" = "https://support.apple.com/en-ca/118102"
"What's new in the updates for iOS/iPadOS 17" = "https://support.apple.com/en-ca/109043"

[iOS."16"]
"What's new for enterprise in iOS/iPadOS 16" = "https://support.apple.com/en-ca/101584"
"What's new in the updates for iOS/iPadOS 16" = "https://support.apple.com/en-ca/101566"

[Common]
"Apple security releases" = "https://support.apple.com/en-ca/100100"
"Apple Platform Deployment" = "https://support.apple.com/en-ca/guide/deployment/dep9d814c555/1/web/1.0"
"Apple Platform Security" = "https://support.apple.com/en-ca/guide/security/secb82d6b274/web"
"Apple Platform Certifications" = "https://support.apple.com/en-ca/guide/certifications/apc353b1b736/web"
"AppleSeed for IT" = "https://beta.apple.com/for-it"

["Apple Guides"]
description = "Find comprehensive guides to deploy, secure, and certify Apple platforms."

["Apple Guides".links]
"Apple Platform Deployment" = "https://support.apple.com/en-ca/guide/deployment/welcome/web"
"Apple Platform Security" = "https://support.apple.com/en-ca/guide/security/welcome/web"
"Apple Platform Certifications" = "https://support.apple.com/en-ca/guide/certifications/welcome/web"
"Apple security releases" = "https://support.apple.com/en-ca/100100"
"Apple products on enterprise networks" = "https://support.apple.com/en-ca/101555"
"Apple Business Manager User Guide" = "https://support.apple.com/en-ca/guide/apple-business-manager/welcome/web"

["Apple Training"]
description = "Explore training tutorials for Apple device support, deployment, management, and more."

["Apple Training".links]
"Apple Device Support Tutorials" = "https://it-training.apple.com/tutorials/apt-support/"
"Deployment and Management Tutorials" = "https://it-training.apple.com/tutorials/apt-deployment/"
"Mac Security Compliance Tutorials" = "https://it-training.apple.com/tutorials/apt-compliance/"
"Apple Business Essentials Tutorials" = "https://it-training.apple.com/tutorials/apt-business-essentials/"

["Apple Developer"]
description = "Resources for Apple developers including beta programs and GitHub repositories."
"Apple Beta Software Program" = "https://beta.apple.com"
"Apple Developer Program" = "https://developer.apple.com/programs/"
"Device Management (GitHub)" = "https://github.com/apple/device-management"

["Apple Developer".context]
"Apple Beta Software Program" = "Contribute to shaping future releases of iOS, iPadOS, macOS, tvOS, watchOS, and HomePod software by testing pre-release versions."
"Apple Developer Program" = "The Apple Developer program provides developers and admins with tools for app creation, code signing, distribution, testing, analytics, and more."
"Device Management (GitHub)" = "Apple Device management schema data for MDM and Declarative Device management (DDM)."

[Security]
description = "Security resources including macOS Security Compliance Project and MITRE ATT&CK."
mSCP = "https://github.com/usnistgov/macos_security"
Mitre = "https://attack.mitre.org/matrices/enterprise/macos/"

[Security.context]
Mitre = "The Mitre macOS Matrix is a compilation of tactics and techniques derived from the MITRE ATT&CKÂ® Matrix for Enterprise, specifically focusing on macOS platform."
mSCP = "The macOS security compliance project is an open source effort to provide a programmatic approach to generating security guidance."
